export * from './capability-repository'
export * from './evidence-repository'
export * from './odyssey-repository'
export * from './passport-repository'
export * from './institution-repository'
export * from './faculty-repository'
export * from './department-repository'
