/**
 * Syrka Learning — NCERT Class X curriculum-population release (four
 * supplied books, 26 chapters). Every chapter here is original
 * Syrka-authored teaching material — concept framing, guided analysis,
 * activities, and transfer questions — grounded in the real supplied NCERT
 * PDFs but never reproducing their prose. See
 * docs/curriculum/ncert-class-10-inventory.md for the verified book/chapter
 * identities and source hashes, and docs/curriculum/ncert-class-10-ingestion.md
 * for the real Stage B ingestion run this content was reviewed against.
 *
 * This is the first complete curriculum-population release for these four
 * supplied books. It is NOT the full NCERT Class X curriculum — Mathematics,
 * Science, History, the supplementary English reader, and additional
 * language books have not been supplied and are not represented here.
 *
 * Kept deliberately separate from lib/mock-data/learning-seed.ts's Chapter 1
 * Chemistry vertical slice (which retains its own richer Tutor-session /
 * hint-ladder / Evidence fixture) rather than merged into it, so neither
 * fixture set risks silently reshaping the other.
 */
import type {
  LearningCurriculum,
  LearningCourse,
  LearningUnit,
  LearningChapter,
  LearningLesson,
  LearningConcept,
  LearningExplanation,
  WorkedExample,
  LearningActivity,
  LearningActivityKind,
  LearningQuestion,
  LearningSpace,
  LearningDocument,
  LearningDocumentVersion,
  LearningPage,
  SourceReference,
  CapabilityDefinition,
} from '@/lib/campus-types'

const OWNER_ID = 'fac-1'
export const NCERT_CURRICULUM_ID = 'ncert-curriculum-1'

export const ncertCurricula: LearningCurriculum[] = [
  { id: NCERT_CURRICULUM_ID, title: 'NCERT Class X — Demonstration Curriculum', subjectLabel: 'Class X — English, Geography, Economics, Political Science', ownerId: OWNER_ID },
]

/** New Capability domains this release introduces — one per book, matching the existing one-capability-per-demo-chapter grain (see cap-1..cap-6 in lib/mock-data/seed.ts). */
export const ncertCapabilityDefinitions: CapabilityDefinition[] = [
  { id: 'cap-7', name: 'Textual Interpretation and Communication', domain: 'English', description: 'Reading literary and non-fiction text closely and building an evidence-backed interpretation of it.' },
  { id: 'cap-8', name: 'Geographic and Spatial Reasoning', domain: 'Geography', description: 'Classifying and reasoning about resources, regions, and human-environment interaction.' },
  { id: 'cap-9', name: 'Economic Reasoning', domain: 'Economics', description: 'Analysing economic institutions, incentives, and trade-offs using the concepts and cases covered.' },
  { id: 'cap-10', name: 'Constitutional and Political Reasoning', domain: 'Political Science', description: 'Reasoning about institutional design, democratic legitimacy, and social divisions in political life.' },
]

export const ncertCourses: LearningCourse[] = []
export const ncertUnits: LearningUnit[] = []
export const ncertLearningSpaces: LearningSpace[] = []
export const ncertChapters: LearningChapter[] = []
export const ncertLessons: LearningLesson[] = []
export const ncertConcepts: LearningConcept[] = []
export const ncertExplanations: LearningExplanation[] = []
export const ncertExamples: WorkedExample[] = []
export const ncertActivities: LearningActivity[] = []
export const ncertQuestions: LearningQuestion[] = []
export const ncertDocuments: LearningDocument[] = []
export const ncertDocumentVersions: LearningDocumentVersion[] = []
export const ncertPages: LearningPage[] = []
export const ncertSourceReferences: SourceReference[] = []


// ---------------------------------------------------------------------------
// English — First Flight
// ---------------------------------------------------------------------------

ncertCourses.push({ id: 'ncert-course-english', curriculumId: NCERT_CURRICULUM_ID, title: 'English — First Flight', gradeLevel: 'Grade 10' })
ncertUnits.push({ id: 'ncert-unit-english', courseId: 'ncert-course-english', title: 'English — First Flight', order: 1 })
ncertLearningSpaces.push({ id: 'ncert-space-english', title: 'English — First Flight', curriculumId: NCERT_CURRICULUM_ID, ownerId: OWNER_ID, currentVersionId: 'ncert-space-english-v1', lifecycleState: 'published' })
ncertDocuments.push({ id: 'ncert-doc-english', title: 'English — First Flight', sourceLabel: 'NCERT Class X — private development/demonstration corpus only', ownerId: OWNER_ID, currentVersionId: 'ncert-doc-english-v1', publicationStatus: 'published', contentHash: '665f92ea88ea7994549e277eafb8e779adcbd06b61e2c13f38e17f45f834858f', sourceType: 'textbook', accessClassification: 'institution_private', processingState: 'extracted', sourceRightsDeclaration: 'development_demonstration_only' })
ncertDocumentVersions.push({ id: 'ncert-doc-english-v1', documentId: 'ncert-doc-english', version: 1, createdAt: '2026-07-27T00:00:00.000Z', extractionMethod: 'native_pdf', extractionProvider: 'native_pdf_v1' })
ncertPages.push({ id: 'ncert-page-eng-1', documentVersionId: 'ncert-doc-english-v1', pageNumber: 3, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-1', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-1', pageId: 'ncert-page-eng-1', excerpt: '[demonstration excerpt — see jeff101.pdf p.3]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-1', unitId: 'ncert-unit-english', title: 'A Letter to God', order: 1, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-1', chapterId: 'ncert-chapter-eng-1', title: 'A Letter to God', order: 1, conceptIds: ['ncert-concept-eng-1-1', 'ncert-concept-eng-1-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-1-1', title: 'Narrative irony', description: 'The gap between what a character believes is happening and what the reader can see is really happening.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-1-2', title: 'Faith tested by circumstance', description: 'How a character\'s faith is challenged, and sometimes distorted, by an institution\'s imperfect response to it.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-1-1', conceptId: 'ncert-concept-eng-1-1', body: 'A farmer\'s letter addressed to God, asking for help after a hailstorm destroys his crop, and what happens to that letter once it reaches the people who actually have to answer it.', sourceReferenceIds: ['ncert-ref-eng-1'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-1-2', conceptId: 'ncert-concept-eng-1-2', body: 'How a character\'s faith is challenged, and sometimes distorted, by an institution\'s imperfect response to it.', sourceReferenceIds: ['ncert-ref-eng-1'] })
ncertExamples.push({ id: 'ncert-example-eng-1', conceptId: 'ncert-concept-eng-1-1', prompt: 'Guided analysis: Lencho\'s expectation vs. the postmaster\'s response', steps: ['Identify what Lencho believes God will do.', 'Identify what the postmaster and his staff actually do instead.', 'Explain why Lencho reacts to the money the way he does — what does his reaction reveal about his faith?'], sourceReferenceIds: ['ncert-ref-eng-1'] })
ncertActivities.push({ id: 'ncert-activity-eng-1', lessonId: 'ncert-lesson-eng-1', kind: 'writing' as LearningActivityKind, title: 'Write a short response: what does Lencho\'s reaction to the collected money tell us about the nature of his faith?', instructions: 'In 150-200 words, explain whether Lencho\'s faith is rewarded, tested, or both — citing at least one specific moment from the story.' })
ncertQuestions.push({ id: 'ncert-question-eng-1-transfer', conceptId: 'ncert-concept-eng-1-1', kind: 'transfer', prompt: 'Apply the same idea (faith tested by an imperfect response) to a different situation you know of — real or fictional — where someone\'s trust in an institution was tested by how imperfectly people carried out their intentions.', answerKeyEntryId: 'ncert-answerkey-eng-1-transfer', sourceReferenceIds: ['ncert-ref-eng-1'] })
// eng-1: source jeff1dd/jeff101.pdf sha256=2554abf66b90cc88...
ncertPages.push({ id: 'ncert-page-eng-2', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-2', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-2', pageId: 'ncert-page-eng-2', excerpt: '[demonstration excerpt — see jeff102.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-2', unitId: 'ncert-unit-english', title: 'Nelson Mandela: Long Walk to Freedom', order: 2, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-2', chapterId: 'ncert-chapter-eng-2', title: 'Nelson Mandela: Long Walk to Freedom', order: 1, conceptIds: ['ncert-concept-eng-2-1', 'ncert-concept-eng-2-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-2-1', title: 'Autobiographical voice', description: 'Writing that reflects on one\'s own life while also making a broader public argument — here, about freedom and courage.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-2-2', title: 'Courage as an earned virtue', description: 'Mandela\'s specific claim that courage is not the absence of fear but the triumph over it — a definition, not just a description.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-2-1', conceptId: 'ncert-concept-eng-2-1', body: 'An excerpt from Mandela\'s autobiography, delivered as a speech on the day of his inauguration, that redefines courage not as fearlessness but as something else entirely.', sourceReferenceIds: ['ncert-ref-eng-2'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-2-2', conceptId: 'ncert-concept-eng-2-2', body: 'Mandela\'s specific claim that courage is not the absence of fear but the triumph over it — a definition, not just a description.', sourceReferenceIds: ['ncert-ref-eng-2'] })
ncertExamples.push({ id: 'ncert-example-eng-2', conceptId: 'ncert-concept-eng-2-1', prompt: 'Guided analysis: Mandela\'s definition of courage', steps: ['Locate the sentence where Mandela defines courage.', 'Contrast that definition with a more common assumption about what courage means.', 'Identify one moment in the excerpt where Mandela applies his own definition to himself.'], sourceReferenceIds: ['ncert-ref-eng-2'] })
ncertActivities.push({ id: 'ncert-activity-eng-2', lessonId: 'ncert-lesson-eng-2', kind: 'writing' as LearningActivityKind, title: 'Discuss: why does Mandela insist that "the brave man is not he who does not feel afraid, but he who conquers that fear"?', instructions: 'In discussion, explain what obligation Mandela says freedom imposes on the free, and why he frames it as an obligation rather than a reward.' })
ncertQuestions.push({ id: 'ncert-question-eng-2-transfer', conceptId: 'ncert-concept-eng-2-1', kind: 'transfer', prompt: 'Apply Mandela\'s definition of courage to a different historical or public figure you know of — does their actions fit his definition, or a different one?', answerKeyEntryId: 'ncert-answerkey-eng-2-transfer', sourceReferenceIds: ['ncert-ref-eng-2'] })
// eng-2: source jeff1dd/jeff102.pdf sha256=10f97cb3c26f8bd3...
ncertPages.push({ id: 'ncert-page-eng-3', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-3', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-3', pageId: 'ncert-page-eng-3', excerpt: '[demonstration excerpt — see jeff103.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-3', unitId: 'ncert-unit-english', title: 'Two Stories about Flying', order: 3, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-3', chapterId: 'ncert-chapter-eng-3', title: 'Two Stories about Flying', order: 1, conceptIds: ['ncert-concept-eng-3-1', 'ncert-concept-eng-3-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-3-1', title: 'Fear and self-belief', description: 'How each story locates the turning point where a character moves from fear to action.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-3-2', title: 'Narrative parallelism', description: 'Why two otherwise unrelated stories are taught together — what common structure or theme links them.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-3-1', conceptId: 'ncert-concept-eng-3-1', body: 'Two short, unrelated stories — a young seagull learning to fly, and a wartime pilot recalling a moment of fear at altitude — placed side by side because both are about conquering fear in the air.', sourceReferenceIds: ['ncert-ref-eng-3'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-3-2', conceptId: 'ncert-concept-eng-3-2', body: 'Why two otherwise unrelated stories are taught together — what common structure or theme links them.', sourceReferenceIds: ['ncert-ref-eng-3'] })
ncertExamples.push({ id: 'ncert-example-eng-3', conceptId: 'ncert-concept-eng-3-1', prompt: 'Guided analysis: the turning point in each story', steps: ['Identify the moment the seagull first flies.', 'Identify the moment the pilot in "Black Aeroplane" faces a comparable turning point.', 'Compare what triggers each character\'s shift from fear to action.'], sourceReferenceIds: ['ncert-ref-eng-3'] })
ncertActivities.push({ id: 'ncert-activity-eng-3', lessonId: 'ncert-lesson-eng-3', kind: 'writing' as LearningActivityKind, title: 'Write a short comparison of how each story\'s protagonist overcomes fear, and whether the trigger is internal or external.', instructions: 'Compare the seagull\'s hunger-driven first flight with the pilot\'s crisis-driven decision — which trigger for courage do you find more convincing, and why?' })
ncertQuestions.push({ id: 'ncert-question-eng-3-transfer', conceptId: 'ncert-concept-eng-3-1', kind: 'transfer', prompt: 'Describe a different situation (real or invented) where fear is overcome by necessity rather than confidence, the way both protagonists\' fears are.', answerKeyEntryId: 'ncert-answerkey-eng-3-transfer', sourceReferenceIds: ['ncert-ref-eng-3'] })
// eng-3: source jeff1dd/jeff103.pdf sha256=074ad18280788501...
ncertPages.push({ id: 'ncert-page-eng-4', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-4', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-4', pageId: 'ncert-page-eng-4', excerpt: '[demonstration excerpt — see jeff104.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-4', unitId: 'ncert-unit-english', title: 'From the Diary of Anne Frank', order: 4, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-4', chapterId: 'ncert-chapter-eng-4', title: 'From the Diary of Anne Frank', order: 1, conceptIds: ['ncert-concept-eng-4-1', 'ncert-concept-eng-4-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-4-1', title: 'Diary as a literary form', description: 'How addressing the diary to an imagined friend ("Kitty") shapes its tone, differently from either private journaling or public autobiography.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-4-2', title: 'Voice under confinement', description: 'How Anne\'s humour, self-criticism, and observation of the people around her persist despite the confined, dangerous circumstances.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-4-1', conceptId: 'ncert-concept-eng-4-1', body: 'An extract from the diary Anne Frank kept while in hiding, read here as both a personal document and a piece of literature with its own narrative voice and audience ("Kitty").', sourceReferenceIds: ['ncert-ref-eng-4'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-4-2', conceptId: 'ncert-concept-eng-4-2', body: 'How Anne\'s humour, self-criticism, and observation of the people around her persist despite the confined, dangerous circumstances.', sourceReferenceIds: ['ncert-ref-eng-4'] })
ncertExamples.push({ id: 'ncert-example-eng-4', conceptId: 'ncert-concept-eng-4-1', prompt: 'Guided analysis: why Anne addresses "Kitty"', steps: ['Identify what effect writing to "Kitty" has on the diary\'s tone.', 'Find one passage where Anne observes another person sharply.', 'Explain what that observation reveals about Anne\'s own situation.'], sourceReferenceIds: ['ncert-ref-eng-4'] })
ncertActivities.push({ id: 'ncert-activity-eng-4', lessonId: 'ncert-lesson-eng-4', kind: 'writing' as LearningActivityKind, title: 'Write in Anne\'s voice a short diary entry addressed to "Kitty" about one other person confined with her, in her observational style.', instructions: 'Explain, citing the text, why a diary written to an imagined friend can still function as a historical document — what does it capture that a formal record could not?' })
ncertQuestions.push({ id: 'ncert-question-eng-4-transfer', conceptId: 'ncert-concept-eng-4-1', kind: 'transfer', prompt: 'Apply the idea of "voice under confinement" to a different first-person account you know of, written under constrained or dangerous circumstances.', answerKeyEntryId: 'ncert-answerkey-eng-4-transfer', sourceReferenceIds: ['ncert-ref-eng-4'] })
// eng-4: source jeff1dd/jeff104.pdf sha256=5cd74b1bdfb065d0...
ncertPages.push({ id: 'ncert-page-eng-5', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-5', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-5', pageId: 'ncert-page-eng-5', excerpt: '[demonstration excerpt — see jeff105.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-5', unitId: 'ncert-unit-english', title: 'Glimpses of India', order: 5, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-5', chapterId: 'ncert-chapter-eng-5', title: 'Glimpses of India', order: 1, conceptIds: ['ncert-concept-eng-5-1', 'ncert-concept-eng-5-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-5-1', title: 'Regional identity through everyday detail', description: 'How each essay conveys a place\'s identity through specific, small details (a baker\'s bell, a particular custom, a leaf) rather than broad claims.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-5-2', title: 'Descriptive/informative prose', description: 'The difference between prose written to inform (facts about a place) and prose written to evoke (what it feels like to be there) — and how these three essays blend both.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-5-1', conceptId: 'ncert-concept-eng-5-1', body: 'Three short, independent essays — on Goan bakers, on Coorg, and on Assam tea — each built from concrete, everyday detail rather than general description of "India."', sourceReferenceIds: ['ncert-ref-eng-5'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-5-2', conceptId: 'ncert-concept-eng-5-2', body: 'The difference between prose written to inform (facts about a place) and prose written to evoke (what it feels like to be there) — and how these three essays blend both.', sourceReferenceIds: ['ncert-ref-eng-5'] })
ncertExamples.push({ id: 'ncert-example-eng-5', conceptId: 'ncert-concept-eng-5-1', prompt: 'Guided analysis: one specific detail per essay', steps: ['Identify one concrete sensory detail from the Goa essay.', 'Identify one from the Coorg essay.', 'Explain what each detail does that a general statement ("Goa has bakers") would not.'], sourceReferenceIds: ['ncert-ref-eng-5'] })
ncertActivities.push({ id: 'ncert-activity-eng-5', lessonId: 'ncert-lesson-eng-5', kind: 'writing' as LearningActivityKind, title: 'Write a short paragraph about a place you know, built from one specific concrete detail rather than a general description.', instructions: 'Choose one of the three essays and explain how its specific details build a larger impression of the region\'s identity — cite at least one detail directly.' })
ncertQuestions.push({ id: 'ncert-question-eng-5-transfer', conceptId: 'ncert-concept-eng-5-1', kind: 'transfer', prompt: 'Apply the same technique (identity through one concrete detail) to describe a place, community, or tradition you know personally.', answerKeyEntryId: 'ncert-answerkey-eng-5-transfer', sourceReferenceIds: ['ncert-ref-eng-5'] })
// eng-5: source jeff1dd/jeff105.pdf sha256=16d0fd9ebf13d20b...
ncertPages.push({ id: 'ncert-page-eng-6', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-6', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-6', pageId: 'ncert-page-eng-6', excerpt: '[demonstration excerpt — see jeff106.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-6', unitId: 'ncert-unit-english', title: 'Mijbil the Otter', order: 6, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-6', chapterId: 'ncert-chapter-eng-6', title: 'Mijbil the Otter', order: 1, conceptIds: ['ncert-concept-eng-6-1', 'ncert-concept-eng-6-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-6-1', title: 'Human-animal relationship', description: 'How the narrator\'s growing attachment to Mijbil is shown through incident and behaviour rather than stated directly.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-6-2', title: 'Descriptive narrative structuring', description: 'How a true story with no single climax is held together by sequence and escalating detail instead of plot tension.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-6-1', conceptId: 'ncert-concept-eng-6-1', body: 'A naturalist\'s account of acquiring and living with a pet otter, told through a long, often comic sequence of everyday incidents rather than a single dramatic event.', sourceReferenceIds: ['ncert-ref-eng-6'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-6-2', conceptId: 'ncert-concept-eng-6-2', body: 'How a true story with no single climax is held together by sequence and escalating detail instead of plot tension.', sourceReferenceIds: ['ncert-ref-eng-6'] })
ncertExamples.push({ id: 'ncert-example-eng-6', conceptId: 'ncert-concept-eng-6-1', prompt: 'Guided analysis: sequencing Mijbil\'s introduction', steps: ['List, in order, three key incidents in Mijbil\'s introduction to the narrator\'s household.', 'Identify what each incident reveals about Mijbil\'s character.', 'Explain how the sequence builds the narrator\'s (and the reader\'s) affection for Mijbil.'], sourceReferenceIds: ['ncert-ref-eng-6'] })
ncertActivities.push({ id: 'ncert-activity-eng-6', lessonId: 'ncert-lesson-eng-6', kind: 'writing' as LearningActivityKind, title: 'Build a short sequence chart of Mijbil\'s key incidents, noting what each one reveals about him.', instructions: 'Explain how the narrator\'s attitude toward Mijbil changes across the incidents described, using the sequence to support your answer.' })
ncertQuestions.push({ id: 'ncert-question-eng-6-transfer', conceptId: 'ncert-concept-eng-6-1', kind: 'transfer', prompt: 'Apply the same "affection built through incident, not statement" technique to describe a pet, animal, or person you know.', answerKeyEntryId: 'ncert-answerkey-eng-6-transfer', sourceReferenceIds: ['ncert-ref-eng-6'] })
// eng-6: source jeff1dd/jeff106.pdf sha256=44935ba5b7241559...
ncertPages.push({ id: 'ncert-page-eng-7', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-7', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-7', pageId: 'ncert-page-eng-7', excerpt: '[demonstration excerpt — see jeff107.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-7', unitId: 'ncert-unit-english', title: 'Madam Rides the Bus', order: 7, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-7', chapterId: 'ncert-chapter-eng-7', title: 'Madam Rides the Bus', order: 1, conceptIds: ['ncert-concept-eng-7-1', 'ncert-concept-eng-7-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-7-1', title: 'Coming-of-age moment', description: 'How a single, small journey is used to mark a shift in a character\'s understanding of the world, without any explicit "lesson" being stated.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-7-2', title: 'Symbolic journey', description: 'How the physical bus journey doubles as a symbolic one — away from safety, toward a wider and less certain world.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-7-1', conceptId: 'ncert-concept-eng-7-1', body: 'An eight-year-old girl\'s first solo bus journey away from her village, framed as both an ordinary trip and her private introduction to ideas of independence, risk, and mortality.', sourceReferenceIds: ['ncert-ref-eng-7'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-7-2', conceptId: 'ncert-concept-eng-7-2', body: 'How the physical bus journey doubles as a symbolic one — away from safety, toward a wider and less certain world.', sourceReferenceIds: ['ncert-ref-eng-7'] })
ncertExamples.push({ id: 'ncert-example-eng-7', conceptId: 'ncert-concept-eng-7-1', prompt: 'Guided analysis: what the journey represents beyond travel', steps: ['Identify what Valli notices during the journey that a typical passenger might not.', 'Identify the moment mortality or risk enters her thinking.', 'Explain what the journey has changed in her by the final page.'], sourceReferenceIds: ['ncert-ref-eng-7'] })
ncertActivities.push({ id: 'ncert-activity-eng-7', lessonId: 'ncert-lesson-eng-7', kind: 'writing' as LearningActivityKind, title: 'Discuss what specifically makes this "just a bus ride" also a coming-of-age moment for Valli.', instructions: 'Explain, with reference to specific moments, what Valli understands by the end of the journey that she did not understand before it began.' })
ncertQuestions.push({ id: 'ncert-question-eng-7-transfer', conceptId: 'ncert-concept-eng-7-1', kind: 'transfer', prompt: 'Describe a different small, ordinary event (real or invented) that functions as a quiet coming-of-age moment, the way this bus ride does for Valli.', answerKeyEntryId: 'ncert-answerkey-eng-7-transfer', sourceReferenceIds: ['ncert-ref-eng-7'] })
// eng-7: source jeff1dd/jeff107.pdf sha256=960643fa97f13ce5...
ncertPages.push({ id: 'ncert-page-eng-8', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-8', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-8', pageId: 'ncert-page-eng-8', excerpt: '[demonstration excerpt — see jeff108.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-8', unitId: 'ncert-unit-english', title: 'The Sermon at Benares', order: 8, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-8', chapterId: 'ncert-chapter-eng-8', title: 'The Sermon at Benares', order: 1, conceptIds: ['ncert-concept-eng-8-1', 'ncert-concept-eng-8-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-8-1', title: 'Parable as teaching device', description: 'Why the Buddha answers Kisa Gotami\'s request with a task (find a house untouched by death) rather than an argument or refusal.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-8-2', title: 'Universality of loss', description: 'How the sermon\'s point depends on Kisa Gotami discovering the truth herself, through the failed search, rather than being told it directly.', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-8-1', conceptId: 'ncert-concept-eng-8-1', body: 'The story of Kisa Gotami, who seeks the Buddha for a cure for her dead child, and the parable he offers her instead of a direct answer.', sourceReferenceIds: ['ncert-ref-eng-8'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-8-2', conceptId: 'ncert-concept-eng-8-2', body: 'How the sermon\'s point depends on Kisa Gotami discovering the truth herself, through the failed search, rather than being told it directly.', sourceReferenceIds: ['ncert-ref-eng-8'] })
ncertExamples.push({ id: 'ncert-example-eng-8', conceptId: 'ncert-concept-eng-8-1', prompt: 'Guided analysis: why the mustard-seed task, not a direct answer', steps: ['Identify what Kisa Gotami asks the Buddha for.', 'Identify the exact task he sets her instead.', 'Explain why the task itself is the answer, and a direct refusal would not have worked as well.'], sourceReferenceIds: ['ncert-ref-eng-8'] })
ncertActivities.push({ id: 'ncert-activity-eng-8', lessonId: 'ncert-lesson-eng-8', kind: 'writing' as LearningActivityKind, title: 'Discuss why the Buddha\'s method (a task, not an argument) is more persuasive here than a direct statement of the same truth would be.', instructions: 'Compare this method of teaching through experience with a different way the same lesson (that loss is universal) could have been delivered — which is more effective, and why?' })
ncertQuestions.push({ id: 'ncert-question-eng-8-transfer', conceptId: 'ncert-concept-eng-8-1', kind: 'transfer', prompt: 'Apply the same idea (a truth better discovered than told) to a different situation where showing, not telling, changes someone\'s understanding.', answerKeyEntryId: 'ncert-answerkey-eng-8-transfer', sourceReferenceIds: ['ncert-ref-eng-8'] })
// eng-8: source jeff1dd/jeff108.pdf sha256=0f27cf046f361234...
ncertPages.push({ id: 'ncert-page-eng-9', documentVersionId: 'ncert-doc-english-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eng-9', documentId: 'ncert-doc-english', documentVersionId: 'ncert-doc-english-v1', chapterId: 'ncert-chapter-eng-9', pageId: 'ncert-page-eng-9', excerpt: '[demonstration excerpt — see jeff109.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eng-9', unitId: 'ncert-unit-english', title: 'The Proposal', order: 9, sourceDocumentId: 'ncert-doc-english' })
ncertLessons.push({ id: 'ncert-lesson-eng-9', chapterId: 'ncert-chapter-eng-9', title: 'The Proposal', order: 1, conceptIds: ['ncert-concept-eng-9-1', 'ncert-concept-eng-9-2'] })
ncertConcepts.push({ id: 'ncert-concept-eng-9-1', title: 'Dramatic irony in comedy', description: 'How the audience can see the marriage proposal is the real goal even while the characters themselves keep losing sight of it in trivial disputes.', domain: 'English' })
ncertConcepts.push({ id: 'ncert-concept-eng-9-2', title: 'Character motivation vs. stated motivation', description: 'The difference between what each character claims to be arguing about (land, a dog) and what is actually driving their behaviour (anxiety about the proposal itself).', domain: 'English' })
ncertExplanations.push({ id: 'ncert-explanation-eng-9-1', conceptId: 'ncert-concept-eng-9-1', body: 'A short comic play in which a marriage proposal is repeatedly derailed by trivial arguments — over a disputed field, then over whose dog is better — that stand in for the characters\' real anxieties.', sourceReferenceIds: ['ncert-ref-eng-9'] })
ncertExplanations.push({ id: 'ncert-explanation-eng-9-2', conceptId: 'ncert-concept-eng-9-2', body: 'The difference between what each character claims to be arguing about (land, a dog) and what is actually driving their behaviour (anxiety about the proposal itself).', sourceReferenceIds: ['ncert-ref-eng-9'] })
ncertExamples.push({ id: 'ncert-example-eng-9', conceptId: 'ncert-concept-eng-9-1', prompt: 'Guided analysis: what the field/dog arguments are really about', steps: ['Identify the stated subject of each argument (the field, then the dog).', 'Identify what each character is avoiding by arguing about something else.', 'Explain how the comedy depends on the audience seeing this gap.'], sourceReferenceIds: ['ncert-ref-eng-9'] })
ncertActivities.push({ id: 'ncert-activity-eng-9', lessonId: 'ncert-lesson-eng-9', kind: 'writing' as LearningActivityKind, title: 'Discuss: what are Lomov and Natalya\'s arguments actually about, beneath their stated subjects?', instructions: 'Choose one argument in the play and explain what it reveals about the character\'s real motivation, as distinct from what they claim to be arguing about.' })
ncertQuestions.push({ id: 'ncert-question-eng-9-transfer', conceptId: 'ncert-concept-eng-9-1', kind: 'transfer', prompt: 'Describe a different situation (real or invented) where an argument over something trivial is really about something else entirely.', answerKeyEntryId: 'ncert-answerkey-eng-9-transfer', sourceReferenceIds: ['ncert-ref-eng-9'] })
// eng-9: source jeff1dd/jeff109.pdf sha256=e782b17e4a777d8d...

// ---------------------------------------------------------------------------
// Geography — Contemporary India II
// ---------------------------------------------------------------------------

ncertCourses.push({ id: 'ncert-course-geography', curriculumId: NCERT_CURRICULUM_ID, title: 'Geography — Contemporary India II', gradeLevel: 'Grade 10' })
ncertUnits.push({ id: 'ncert-unit-geography', courseId: 'ncert-course-geography', title: 'Geography — Contemporary India II', order: 1 })
ncertLearningSpaces.push({ id: 'ncert-space-geography', title: 'Geography — Contemporary India II', curriculumId: NCERT_CURRICULUM_ID, ownerId: OWNER_ID, currentVersionId: 'ncert-space-geography-v1', lifecycleState: 'published' })
ncertDocuments.push({ id: 'ncert-doc-geography', title: 'Geography — Contemporary India II', sourceLabel: 'NCERT Class X — private development/demonstration corpus only', ownerId: OWNER_ID, currentVersionId: 'ncert-doc-geography-v1', publicationStatus: 'published', contentHash: '49863325d9e0be6339eccbbd1a8604dd1e7ef3c3f3d6d279d42449da68296eca', sourceType: 'textbook', accessClassification: 'institution_private', processingState: 'extracted', sourceRightsDeclaration: 'development_demonstration_only' })
ncertDocumentVersions.push({ id: 'ncert-doc-geography-v1', documentId: 'ncert-doc-geography', version: 1, createdAt: '2026-07-27T00:00:00.000Z', extractionMethod: 'native_pdf', extractionProvider: 'native_pdf_v1' })
ncertPages.push({ id: 'ncert-page-geo-1', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-1', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-1', pageId: 'ncert-page-geo-1', excerpt: '[demonstration excerpt — see jess101.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-1', unitId: 'ncert-unit-geography', title: 'Resources and Development', order: 1, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-1', chapterId: 'ncert-chapter-geo-1', title: 'Resources and Development', order: 1, conceptIds: ['ncert-concept-geo-1-1', 'ncert-concept-geo-1-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-1-1', title: 'Resource classification', description: 'Resources are classified by origin (biotic/abiotic), exhaustibility (renewable/non-renewable), ownership (individual/community/national/international), and stage of development (potential/developed/stock/reserve).', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-1-2', title: 'Sustainable development', description: 'Development that meets present needs without compromising the ability of future generations to meet their own — applied here to land and soil degradation specifically.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-1-1', conceptId: 'ncert-concept-geo-1-1', body: 'What counts as a "resource" is not fixed — it depends on technology, economics, and culture — and how resources get classified, planned for, and used sustainably.', sourceReferenceIds: ['ncert-ref-geo-1'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-1-2', conceptId: 'ncert-concept-geo-1-2', body: 'Development that meets present needs without compromising the ability of future generations to meet their own — applied here to land and soil degradation specifically.', sourceReferenceIds: ['ncert-ref-geo-1'] })
ncertExamples.push({ id: 'ncert-example-geo-1', conceptId: 'ncert-concept-geo-1-1', prompt: 'Guided analysis: why a substance becomes a "resource"', steps: ['Identify a substance that was not historically considered a resource.', 'Identify what changed (technology, need, or value) to make it one.', 'Explain how this shows resources are defined relative to human capability, not fixed by nature.'], sourceReferenceIds: ['ncert-ref-geo-1'] })
ncertActivities.push({ id: 'ncert-activity-geo-1', lessonId: 'ncert-lesson-geo-1', kind: 'project' as LearningActivityKind, title: 'Build a simple classification table sorting five named resources by origin, exhaustibility, and ownership.', instructions: 'Using the classification framework, explain why a resource\'s exhaustibility can change as extraction technology or consumption rates change.' })
ncertQuestions.push({ id: 'ncert-question-geo-1-transfer', conceptId: 'ncert-concept-geo-1-1', kind: 'transfer', prompt: 'Apply the "resources are defined relative to capability" idea to a substance or material not covered in this chapter.', answerKeyEntryId: 'ncert-answerkey-geo-1-transfer', sourceReferenceIds: ['ncert-ref-geo-1'] })
// geo-1: source jess1dd/jess1dd/jess101.pdf sha256=e2d7e9e470c73663...
ncertPages.push({ id: 'ncert-page-geo-2', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-2', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-2', pageId: 'ncert-page-geo-2', excerpt: '[demonstration excerpt — see jess102.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-2', unitId: 'ncert-unit-geography', title: 'Forest and Wildlife Resources', order: 2, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-2', chapterId: 'ncert-chapter-geo-2', title: 'Forest and Wildlife Resources', order: 1, conceptIds: ['ncert-concept-geo-2-1', 'ncert-concept-geo-2-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-2-1', title: 'Biodiversity conservation categories', description: 'The classification of species as normal, endangered, vulnerable, rare, endemic, or extinct, and why this classification matters for conservation priority.', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-2-2', title: 'Community-based conservation', description: 'How local community participation (rather than only government protection) has proven effective in specific conservation efforts described in the chapter.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-2-1', conceptId: 'ncert-concept-geo-2-1', body: 'India\'s biodiversity and the categories used to classify species by conservation risk, alongside real community-based approaches to protecting habitats.', sourceReferenceIds: ['ncert-ref-geo-2'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-2-2', conceptId: 'ncert-concept-geo-2-2', body: 'How local community participation (rather than only government protection) has proven effective in specific conservation efforts described in the chapter.', sourceReferenceIds: ['ncert-ref-geo-2'] })
ncertExamples.push({ id: 'ncert-example-geo-2', conceptId: 'ncert-concept-geo-2-1', prompt: 'Guided analysis: why classification affects conservation priority', steps: ['Identify the difference between an endangered and a vulnerable species by definition.', 'Explain why a species\' classification changes the urgency of protecting it.', 'Identify one community-based conservation example from the chapter.'], sourceReferenceIds: ['ncert-ref-geo-2'] })
ncertActivities.push({ id: 'ncert-activity-geo-2', lessonId: 'ncert-lesson-geo-2', kind: 'project' as LearningActivityKind, title: 'Classify three named species from the chapter using the conservation-status categories, and justify each classification.', instructions: 'Explain, using the classification framework, why endemic species require a different conservation approach than widely distributed ones.' })
ncertQuestions.push({ id: 'ncert-question-geo-2-transfer', conceptId: 'ncert-concept-geo-2-1', kind: 'transfer', prompt: 'Apply the community-based conservation model described in the chapter to a different conservation problem (real or hypothetical) you can identify.', answerKeyEntryId: 'ncert-answerkey-geo-2-transfer', sourceReferenceIds: ['ncert-ref-geo-2'] })
// geo-2: source jess1dd/jess1dd/jess102.pdf sha256=bab59f420ede000b...
ncertPages.push({ id: 'ncert-page-geo-3', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-3', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-3', pageId: 'ncert-page-geo-3', excerpt: '[demonstration excerpt — see jess103.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-3', unitId: 'ncert-unit-geography', title: 'Water Resources', order: 3, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-3', chapterId: 'ncert-chapter-geo-3', title: 'Water Resources', order: 1, conceptIds: ['ncert-concept-geo-3-1', 'ncert-concept-geo-3-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-3-1', title: 'Water scarcity causes', description: 'Scarcity can result from over-exploitation, excessive use, and unequal access — not only from a low absolute quantity of available water.', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-3-2', title: 'Multi-purpose river projects', description: 'Dams designed to serve irrigation, power generation, flood control, and water supply simultaneously — and the trade-offs and criticisms this multi-purpose design creates.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-3-1', conceptId: 'ncert-concept-geo-3-1', body: 'Why water scarcity exists even where water is not physically absent, and how multi-purpose river projects attempt (and sometimes fail) to solve several problems at once.', sourceReferenceIds: ['ncert-ref-geo-3'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-3-2', conceptId: 'ncert-concept-geo-3-2', body: 'Dams designed to serve irrigation, power generation, flood control, and water supply simultaneously — and the trade-offs and criticisms this multi-purpose design creates.', sourceReferenceIds: ['ncert-ref-geo-3'] })
ncertExamples.push({ id: 'ncert-example-geo-3', conceptId: 'ncert-concept-geo-3-1', prompt: 'Guided analysis: scarcity despite sufficient water', steps: ['Identify a region or scenario in the chapter where water is scarce despite adequate rainfall.', 'Identify which of the three causes (over-exploitation, excess use, unequal access) is most responsible.', 'Explain why "more water" alone would not solve that specific scarcity.'], sourceReferenceIds: ['ncert-ref-geo-3'] })
ncertActivities.push({ id: 'ncert-activity-geo-3', lessonId: 'ncert-lesson-geo-3', kind: 'project' as LearningActivityKind, title: 'Build a cause-and-effect chain from one water-scarcity cause described in the chapter to its social or agricultural consequence.', instructions: 'Explain, using a specific project named in the chapter, why a multi-purpose river project can be simultaneously beneficial and controversial.' })
ncertQuestions.push({ id: 'ncert-question-geo-3-transfer', conceptId: 'ncert-concept-geo-3-1', kind: 'transfer', prompt: 'Apply the "scarcity is not only about quantity" idea to a resource-scarcity situation you know of outside this chapter.', answerKeyEntryId: 'ncert-answerkey-geo-3-transfer', sourceReferenceIds: ['ncert-ref-geo-3'] })
// geo-3: source jess1dd/jess1dd/jess103.pdf sha256=87d91ba2705d8dab...
ncertPages.push({ id: 'ncert-page-geo-4', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-4', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-4', pageId: 'ncert-page-geo-4', excerpt: '[demonstration excerpt — see jess104.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-4', unitId: 'ncert-unit-geography', title: 'Agriculture', order: 4, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-4', chapterId: 'ncert-chapter-geo-4', title: 'Agriculture', order: 1, conceptIds: ['ncert-concept-geo-4-1', 'ncert-concept-geo-4-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-4-1', title: 'Cropping seasons', description: 'The Rabi, Kharif, and Zaid cropping seasons, defined by sowing/harvesting timing and the specific crops associated with each.', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-4-2', title: 'Types of farming', description: 'The distinction between primitive subsistence, intensive subsistence, and commercial farming, based on technology use, labour intensity, and market orientation.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-4-1', conceptId: 'ncert-concept-geo-4-1', body: 'How agriculture is classified by cropping season and by farming method, and what these classifications reveal about regional variation in Indian farming.', sourceReferenceIds: ['ncert-ref-geo-4'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-4-2', conceptId: 'ncert-concept-geo-4-2', body: 'The distinction between primitive subsistence, intensive subsistence, and commercial farming, based on technology use, labour intensity, and market orientation.', sourceReferenceIds: ['ncert-ref-geo-4'] })
ncertExamples.push({ id: 'ncert-example-geo-4', conceptId: 'ncert-concept-geo-4-1', prompt: 'Guided analysis: matching a crop to its correct season', steps: ['Identify one crop associated with the Kharif season and one with Rabi.', 'Explain what climatic condition each season depends on.', 'Identify which farming type is most associated with each crop in the chapter\'s description.'], sourceReferenceIds: ['ncert-ref-geo-4'] })
ncertActivities.push({ id: 'ncert-activity-geo-4', lessonId: 'ncert-lesson-geo-4', kind: 'project' as LearningActivityKind, title: 'Build a table matching five named crops to their cropping season and dominant farming type.', instructions: 'Explain why the same crop can be grown differently (subsistence vs. commercial) in different regions of India, using the chapter\'s classification.' })
ncertQuestions.push({ id: 'ncert-question-geo-4-transfer', conceptId: 'ncert-concept-geo-4-1', kind: 'transfer', prompt: 'Apply the season/farming-type classification framework to a crop grown in your own region, if you know one, or a crop not explicitly covered.', answerKeyEntryId: 'ncert-answerkey-geo-4-transfer', sourceReferenceIds: ['ncert-ref-geo-4'] })
// geo-4: source jess1dd/jess1dd/jess104.pdf sha256=21d1701bba940254...
ncertPages.push({ id: 'ncert-page-geo-5', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-5', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-5', pageId: 'ncert-page-geo-5', excerpt: '[demonstration excerpt — see jess105.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-5', unitId: 'ncert-unit-geography', title: 'Minerals and Energy Resources', order: 5, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-5', chapterId: 'ncert-chapter-geo-5', title: 'Minerals and Energy Resources', order: 1, conceptIds: ['ncert-concept-geo-5-1', 'ncert-concept-geo-5-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-5-1', title: 'Mineral classification', description: 'Minerals classified as metallic (ferrous/non-ferrous) or non-metallic, based on physical/chemical composition, each with distinct extraction and use patterns.', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-5-2', title: 'Conventional vs. non-conventional energy', description: 'The distinction between finite, currently dominant sources (coal, petroleum) and renewable alternatives (solar, wind, biogas), and why the shift matters for long-term planning.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-5-1', conceptId: 'ncert-concept-geo-5-1', body: 'How minerals are classified by composition, and the shift from conventional to non-conventional energy sources as a deliberate resource-planning decision, not just a technology trend.', sourceReferenceIds: ['ncert-ref-geo-5'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-5-2', conceptId: 'ncert-concept-geo-5-2', body: 'The distinction between finite, currently dominant sources (coal, petroleum) and renewable alternatives (solar, wind, biogas), and why the shift matters for long-term planning.', sourceReferenceIds: ['ncert-ref-geo-5'] })
ncertExamples.push({ id: 'ncert-example-geo-5', conceptId: 'ncert-concept-geo-5-1', prompt: 'Guided analysis: classifying a named mineral', steps: ['Identify one ferrous and one non-ferrous mineral from the chapter.', 'Identify their primary industrial use.', 'Explain why the ferrous/non-ferrous distinction matters for how each mineral is processed.'], sourceReferenceIds: ['ncert-ref-geo-5'] })
ncertActivities.push({ id: 'ncert-activity-geo-5', lessonId: 'ncert-lesson-geo-5', kind: 'project' as LearningActivityKind, title: 'Build a classification table sorting five named minerals or energy sources into their correct category.', instructions: 'Explain why a shift toward non-conventional energy sources is described as a planning necessity rather than only an environmental preference.' })
ncertQuestions.push({ id: 'ncert-question-geo-5-transfer', conceptId: 'ncert-concept-geo-5-1', kind: 'transfer', prompt: 'Apply the conventional/non-conventional classification to an energy source used in your own context, if you know one.', answerKeyEntryId: 'ncert-answerkey-geo-5-transfer', sourceReferenceIds: ['ncert-ref-geo-5'] })
// geo-5: source jess1dd/jess1dd/jess105.pdf sha256=f402073762eb9dfd...
ncertPages.push({ id: 'ncert-page-geo-6', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-6', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-6', pageId: 'ncert-page-geo-6', excerpt: '[demonstration excerpt — see jess106.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-6', unitId: 'ncert-unit-geography', title: 'Manufacturing Industries', order: 6, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-6', chapterId: 'ncert-chapter-geo-6', title: 'Manufacturing Industries', order: 1, conceptIds: ['ncert-concept-geo-6-1', 'ncert-concept-geo-6-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-6-1', title: 'Industry classification', description: 'Industries classified by raw material source (agro/mineral-based), ownership (public/private/joint/cooperative), and size/capital (large/small-scale).', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-6-2', title: 'Industrial pollution and control', description: 'The specific categories of industrial pollution (air, water, land, noise) and the control measures the chapter describes for each.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-6-1', conceptId: 'ncert-concept-geo-6-1', body: 'How industries are classified by raw material, ownership, and scale, and the specific pollution-control measures the chapter associates with sustainable industrial development.', sourceReferenceIds: ['ncert-ref-geo-6'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-6-2', conceptId: 'ncert-concept-geo-6-2', body: 'The specific categories of industrial pollution (air, water, land, noise) and the control measures the chapter describes for each.', sourceReferenceIds: ['ncert-ref-geo-6'] })
ncertExamples.push({ id: 'ncert-example-geo-6', conceptId: 'ncert-concept-geo-6-1', prompt: 'Guided analysis: classifying a named industry', steps: ['Identify one agro-based and one mineral-based industry from the chapter.', 'Identify the ownership category the chapter would place each in.', 'Identify one pollution-control measure relevant to that industry\'s main pollutant.'], sourceReferenceIds: ['ncert-ref-geo-6'] })
ncertActivities.push({ id: 'ncert-activity-geo-6', lessonId: 'ncert-lesson-geo-6', kind: 'project' as LearningActivityKind, title: 'Build a classification table sorting five named industries by raw-material basis and ownership.', instructions: 'Explain why a single industry might require more than one type of pollution control simultaneously, using a specific example from the chapter.' })
ncertQuestions.push({ id: 'ncert-question-geo-6-transfer', conceptId: 'ncert-concept-geo-6-1', kind: 'transfer', prompt: 'Apply the industry-classification framework to a manufacturing activity you know of that is not explicitly named in the chapter.', answerKeyEntryId: 'ncert-answerkey-geo-6-transfer', sourceReferenceIds: ['ncert-ref-geo-6'] })
// geo-6: source jess1dd/jess1dd/jess106.pdf sha256=0817faa6575c3e10...
ncertPages.push({ id: 'ncert-page-geo-7', documentVersionId: 'ncert-doc-geography-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-geo-7', documentId: 'ncert-doc-geography', documentVersionId: 'ncert-doc-geography-v1', chapterId: 'ncert-chapter-geo-7', pageId: 'ncert-page-geo-7', excerpt: '[demonstration excerpt — see jess107.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-geo-7', unitId: 'ncert-unit-geography', title: 'Lifelines of National Economy', order: 7, sourceDocumentId: 'ncert-doc-geography' })
ncertLessons.push({ id: 'ncert-lesson-geo-7', chapterId: 'ncert-chapter-geo-7', title: 'Lifelines of National Economy', order: 1, conceptIds: ['ncert-concept-geo-7-1', 'ncert-concept-geo-7-2'] })
ncertConcepts.push({ id: 'ncert-concept-geo-7-1', title: 'Modes of transportation compared', description: 'The comparative advantages of road, rail, water, air, and pipeline transport by cost, speed, and suitability for different goods.', domain: 'Geography' })
ncertConcepts.push({ id: 'ncert-concept-geo-7-2', title: 'Trade and tertiary activities', description: 'Why the chapter treats trade, communication, and other services as economic "lifelines" — activities that connect and enable production rather than producing goods directly.', domain: 'Geography' })
ncertExplanations.push({ id: 'ncert-explanation-geo-7-1', conceptId: 'ncert-concept-geo-7-1', body: 'How different modes of transport compete and complement each other, and why trade and services are described as the true "lifelines" connecting production to consumption.', sourceReferenceIds: ['ncert-ref-geo-7'] })
ncertExplanations.push({ id: 'ncert-explanation-geo-7-2', conceptId: 'ncert-concept-geo-7-2', body: 'Why the chapter treats trade, communication, and other services as economic "lifelines" — activities that connect and enable production rather than producing goods directly.', sourceReferenceIds: ['ncert-ref-geo-7'] })
ncertExamples.push({ id: 'ncert-example-geo-7', conceptId: 'ncert-concept-geo-7-1', prompt: 'Guided analysis: choosing a transport mode for a named good', steps: ['Identify a good described in the chapter (e.g. perishable produce, bulk minerals).', 'Identify which transport mode the chapter associates with moving it efficiently.', 'Explain the comparative-advantage reasoning behind that choice.'], sourceReferenceIds: ['ncert-ref-geo-7'] })
ncertActivities.push({ id: 'ncert-activity-geo-7', lessonId: 'ncert-lesson-geo-7', kind: 'project' as LearningActivityKind, title: 'Build a comparison table of transport modes against cost, speed, and suitable goods, using the chapter\'s own examples.', instructions: 'Explain why the chapter calls trade and communication "lifelines" of the economy rather than simply "sectors," using its own reasoning.' })
ncertQuestions.push({ id: 'ncert-question-geo-7-transfer', conceptId: 'ncert-concept-geo-7-1', kind: 'transfer', prompt: 'Apply the comparative-advantage reasoning for transport-mode choice to a good or route not explicitly named in the chapter.', answerKeyEntryId: 'ncert-answerkey-geo-7-transfer', sourceReferenceIds: ['ncert-ref-geo-7'] })
// geo-7: source jess1dd/jess1dd/jess107.pdf sha256=2628173d9d443003...

// ---------------------------------------------------------------------------
// Economics — Understanding Economic Development
// ---------------------------------------------------------------------------

ncertCourses.push({ id: 'ncert-course-economics', curriculumId: NCERT_CURRICULUM_ID, title: 'Economics — Understanding Economic Development', gradeLevel: 'Grade 10' })
ncertUnits.push({ id: 'ncert-unit-economics', courseId: 'ncert-course-economics', title: 'Economics — Understanding Economic Development', order: 1 })
ncertLearningSpaces.push({ id: 'ncert-space-economics', title: 'Economics — Understanding Economic Development', curriculumId: NCERT_CURRICULUM_ID, ownerId: OWNER_ID, currentVersionId: 'ncert-space-economics-v1', lifecycleState: 'published' })
ncertDocuments.push({ id: 'ncert-doc-economics', title: 'Economics — Understanding Economic Development', sourceLabel: 'NCERT Class X — private development/demonstration corpus only', ownerId: OWNER_ID, currentVersionId: 'ncert-doc-economics-v1', publicationStatus: 'published', contentHash: 'c036d449f632975a0a98e201be947f6cff75fd88c952b4f90bfdd2f04b4ffc10', sourceType: 'textbook', accessClassification: 'institution_private', processingState: 'extracted', sourceRightsDeclaration: 'development_demonstration_only' })
ncertDocumentVersions.push({ id: 'ncert-doc-economics-v1', documentId: 'ncert-doc-economics', version: 1, createdAt: '2026-07-27T00:00:00.000Z', extractionMethod: 'native_pdf', extractionProvider: 'native_pdf_v1' })
ncertPages.push({ id: 'ncert-page-eco-1', documentVersionId: 'ncert-doc-economics-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eco-1', documentId: 'ncert-doc-economics', documentVersionId: 'ncert-doc-economics-v1', chapterId: 'ncert-chapter-eco-1', pageId: 'ncert-page-eco-1', excerpt: '[demonstration excerpt — see jess201.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eco-1', unitId: 'ncert-unit-economics', title: 'Development', order: 1, sourceDocumentId: 'ncert-doc-economics' })
ncertLessons.push({ id: 'ncert-lesson-eco-1', chapterId: 'ncert-chapter-eco-1', title: 'Development', order: 1, conceptIds: ['ncert-concept-eco-1-1', 'ncert-concept-eco-1-2'] })
ncertConcepts.push({ id: 'ncert-concept-eco-1-1', title: 'Differing notions of development', description: 'What counts as development depends on what different people and groups value — the chapter\'s own examples show this is not a single agreed goal.', domain: 'Economics' })
ncertConcepts.push({ id: 'ncert-concept-eco-1-2', title: 'Beyond income comparison', description: 'Why national/per-capita income comparisons can mask real differences in human development (health, literacy, equality) between two places with similar average income.', domain: 'Economics' })
ncertExplanations.push({ id: 'ncert-explanation-eco-1-1', conceptId: 'ncert-concept-eco-1-1', body: 'Why "development" means different things to different people, and why comparing places by average income alone can hide more than it reveals.', sourceReferenceIds: ['ncert-ref-eco-1'] })
ncertExplanations.push({ id: 'ncert-explanation-eco-1-2', conceptId: 'ncert-concept-eco-1-2', body: 'Why national/per-capita income comparisons can mask real differences in human development (health, literacy, equality) between two places with similar average income.', sourceReferenceIds: ['ncert-ref-eco-1'] })
ncertExamples.push({ id: 'ncert-example-eco-1', conceptId: 'ncert-concept-eco-1-1', prompt: 'Guided analysis: two places, same income, different development', steps: ['Identify two hypothetical or real places compared in the chapter with similar average income.', 'Identify one non-income indicator (literacy, life expectancy, etc.) where they differ.', 'Explain why average income alone would have hidden this difference.'], sourceReferenceIds: ['ncert-ref-eco-1'] })
ncertActivities.push({ id: 'ncert-activity-eco-1', lessonId: 'ncert-lesson-eco-1', kind: 'discussion' as LearningActivityKind, title: 'Discuss why two people in the same village might define "development" completely differently.', instructions: 'Using the chapter\'s framework, explain why per-capita income is a necessary but insufficient measure of development on its own.' })
ncertQuestions.push({ id: 'ncert-question-eco-1-transfer', conceptId: 'ncert-concept-eco-1-1', kind: 'transfer', prompt: 'Apply the "development means different things to different people" idea to a real decision or debate you are aware of.', answerKeyEntryId: 'ncert-answerkey-eco-1-transfer', sourceReferenceIds: ['ncert-ref-eco-1'] })
// eco-1: source jess2dd/jess201.pdf sha256=1a6f8af67a416b98...
ncertPages.push({ id: 'ncert-page-eco-2', documentVersionId: 'ncert-doc-economics-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eco-2', documentId: 'ncert-doc-economics', documentVersionId: 'ncert-doc-economics-v1', chapterId: 'ncert-chapter-eco-2', pageId: 'ncert-page-eco-2', excerpt: '[demonstration excerpt — see jess202.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eco-2', unitId: 'ncert-unit-economics', title: 'Sectors of the Indian Economy', order: 2, sourceDocumentId: 'ncert-doc-economics' })
ncertLessons.push({ id: 'ncert-lesson-eco-2', chapterId: 'ncert-chapter-eco-2', title: 'Sectors of the Indian Economy', order: 1, conceptIds: ['ncert-concept-eco-2-1', 'ncert-concept-eco-2-2'] })
ncertConcepts.push({ id: 'ncert-concept-eco-2-1', title: 'Primary/secondary/tertiary classification', description: 'Sectors classified by the nature of activity (extracting/producing/servicing), and how employment has shifted across them over time in India.', domain: 'Economics' })
ncertConcepts.push({ id: 'ncert-concept-eco-2-2', title: 'Organised vs. unorganised sector', description: 'A second, independent classification based on registration, job security, and regulation — cutting across all three activity-based sectors.', domain: 'Economics' })
ncertExplanations.push({ id: 'ncert-explanation-eco-2-1', conceptId: 'ncert-concept-eco-2-1', body: 'How the Indian economy is classified into primary, secondary, and tertiary sectors, and the separate, equally important classification into organised and unorganised sectors.', sourceReferenceIds: ['ncert-ref-eco-2'] })
ncertExplanations.push({ id: 'ncert-explanation-eco-2-2', conceptId: 'ncert-concept-eco-2-2', body: 'A second, independent classification based on registration, job security, and regulation — cutting across all three activity-based sectors.', sourceReferenceIds: ['ncert-ref-eco-2'] })
ncertExamples.push({ id: 'ncert-example-eco-2', conceptId: 'ncert-concept-eco-2-1', prompt: 'Guided analysis: an activity that is primary but unorganised', steps: ['Identify a primary-sector activity described as largely unorganised.', 'Identify what makes it "unorganised" by the chapter\'s definition (no fixed hours, no job security, etc.).', 'Explain why a job can be primary-sector and unorganised at the same time — these are two separate classifications, not one spectrum.'], sourceReferenceIds: ['ncert-ref-eco-2'] })
ncertActivities.push({ id: 'ncert-activity-eco-2', lessonId: 'ncert-lesson-eco-2', kind: 'discussion' as LearningActivityKind, title: 'Discuss why India\'s employment share and its income share across sectors do not match — what does that mismatch reveal?', instructions: 'Using the two classification systems (activity-based and organisation-based), explain why "which sector is largest" depends on which classification you ask about.' })
ncertQuestions.push({ id: 'ncert-question-eco-2-transfer', conceptId: 'ncert-concept-eco-2-1', kind: 'transfer', prompt: 'Apply the organised/unorganised distinction to a job or occupation you know of that is not explicitly discussed in the chapter.', answerKeyEntryId: 'ncert-answerkey-eco-2-transfer', sourceReferenceIds: ['ncert-ref-eco-2'] })
// eco-2: source jess2dd/jess202.pdf sha256=255acd3c637a2392...
ncertPages.push({ id: 'ncert-page-eco-3', documentVersionId: 'ncert-doc-economics-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eco-3', documentId: 'ncert-doc-economics', documentVersionId: 'ncert-doc-economics-v1', chapterId: 'ncert-chapter-eco-3', pageId: 'ncert-page-eco-3', excerpt: '[demonstration excerpt — see jess203.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eco-3', unitId: 'ncert-unit-economics', title: 'Money and Credit', order: 3, sourceDocumentId: 'ncert-doc-economics' })
ncertLessons.push({ id: 'ncert-lesson-eco-3', chapterId: 'ncert-chapter-eco-3', title: 'Money and Credit', order: 1, conceptIds: ['ncert-concept-eco-3-1', 'ncert-concept-eco-3-2'] })
ncertConcepts.push({ id: 'ncert-concept-eco-3-1', title: 'Functions of money', description: 'Money solves the "double coincidence of wants" problem inherent to barter — the chapter\'s specific explanation for why money exists as a medium of exchange.', domain: 'Economics' })
ncertConcepts.push({ id: 'ncert-concept-eco-3-2', title: 'Formal vs. informal credit', description: 'The distinction between bank/cooperative (formal) credit and moneylender/trader (informal) credit — in interest rates, documentation, and the borrower\'s protection.', domain: 'Economics' })
ncertExplanations.push({ id: 'ncert-explanation-eco-3-1', conceptId: 'ncert-concept-eco-3-1', body: 'What money actually does that a barter system could not, and why the source of a loan (a bank vs. a moneylender) changes everything about its terms.', sourceReferenceIds: ['ncert-ref-eco-3'] })
ncertExplanations.push({ id: 'ncert-explanation-eco-3-2', conceptId: 'ncert-concept-eco-3-2', body: 'The distinction between bank/cooperative (formal) credit and moneylender/trader (informal) credit — in interest rates, documentation, and the borrower\'s protection.', sourceReferenceIds: ['ncert-ref-eco-3'] })
ncertExamples.push({ id: 'ncert-example-eco-3', conceptId: 'ncert-concept-eco-3-1', prompt: 'Guided analysis: why a farmer might still borrow informally', steps: ['Identify one advantage formal credit has over informal credit, per the chapter.', 'Identify one reason a borrower might still choose informal credit despite that disadvantage.', 'Explain what this reveals about access to formal credit being unequal, not just a matter of choice.'], sourceReferenceIds: ['ncert-ref-eco-3'] })
ncertActivities.push({ id: 'ncert-activity-eco-3', lessonId: 'ncert-lesson-eco-3', kind: 'discussion' as LearningActivityKind, title: 'Discuss: if formal credit is cheaper, why does informal credit remain so common in the situations the chapter describes?', instructions: 'Using the "double coincidence of wants" idea, explain in your own words what specific problem money solves that barter could not.' })
ncertQuestions.push({ id: 'ncert-question-eco-3-transfer', conceptId: 'ncert-concept-eco-3-1', kind: 'transfer', prompt: 'Apply the formal/informal credit distinction to a borrowing situation you are aware of, real or hypothetical, outside the chapter\'s examples.', answerKeyEntryId: 'ncert-answerkey-eco-3-transfer', sourceReferenceIds: ['ncert-ref-eco-3'] })
// eco-3: source jess2dd/jess203.pdf sha256=ec5383e7501501c2...
ncertPages.push({ id: 'ncert-page-eco-4', documentVersionId: 'ncert-doc-economics-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eco-4', documentId: 'ncert-doc-economics', documentVersionId: 'ncert-doc-economics-v1', chapterId: 'ncert-chapter-eco-4', pageId: 'ncert-page-eco-4', excerpt: '[demonstration excerpt — see jess204.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eco-4', unitId: 'ncert-unit-economics', title: 'Globalisation and the Indian Economy', order: 4, sourceDocumentId: 'ncert-doc-economics' })
ncertLessons.push({ id: 'ncert-lesson-eco-4', chapterId: 'ncert-chapter-eco-4', title: 'Globalisation and the Indian Economy', order: 1, conceptIds: ['ncert-concept-eco-4-1', 'ncert-concept-eco-4-2'] })
ncertConcepts.push({ id: 'ncert-concept-eco-4-1', title: 'Trade and investment liberalisation', description: 'The specific policy changes (removing trade barriers, allowing foreign investment) that the chapter identifies as driving globalisation, distinct from globalisation as a general trend.', domain: 'Economics' })
ncertConcepts.push({ id: 'ncert-concept-eco-4-2', title: 'Winners and losers from globalisation', description: 'The chapter\'s explicit position that globalisation has benefited some producers and workers while displacing others — not a uniformly positive or negative process.', domain: 'Economics' })
ncertExplanations.push({ id: 'ncert-explanation-eco-4-1', conceptId: 'ncert-concept-eco-4-1', body: 'How trade and investment liberalisation connects producers and consumers across countries, and why the chapter insists globalisation produces both winners and losers, not a single uniform outcome.', sourceReferenceIds: ['ncert-ref-eco-4'] })
ncertExplanations.push({ id: 'ncert-explanation-eco-4-2', conceptId: 'ncert-concept-eco-4-2', body: 'The chapter\'s explicit position that globalisation has benefited some producers and workers while displacing others — not a uniformly positive or negative process.', sourceReferenceIds: ['ncert-ref-eco-4'] })
ncertExamples.push({ id: 'ncert-example-eco-4', conceptId: 'ncert-concept-eco-4-1', prompt: 'Guided analysis: one winner, one loser, same policy', steps: ['Identify one group the chapter describes as benefiting from liberalisation.', 'Identify one group described as negatively affected by the same broad policy shift.', 'Explain what specific difference (access to capital, market position, skill) accounts for the different outcomes.'], sourceReferenceIds: ['ncert-ref-eco-4'] })
ncertActivities.push({ id: 'ncert-activity-eco-4', lessonId: 'ncert-lesson-eco-4', kind: 'discussion' as LearningActivityKind, title: 'Discuss why the same trade-liberalisation policy can create very different outcomes for different producers.', instructions: 'Using at least one specific example from the chapter, explain the mechanism by which liberalisation can displace an existing small producer.' })
ncertQuestions.push({ id: 'ncert-question-eco-4-transfer', conceptId: 'ncert-concept-eco-4-1', kind: 'transfer', prompt: 'Apply the "same policy, different outcomes" idea to an economic change or policy you are aware of outside this chapter.', answerKeyEntryId: 'ncert-answerkey-eco-4-transfer', sourceReferenceIds: ['ncert-ref-eco-4'] })
// eco-4: source jess2dd/jess204.pdf sha256=4e3441cb0d7789ae...
ncertPages.push({ id: 'ncert-page-eco-5', documentVersionId: 'ncert-doc-economics-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-eco-5', documentId: 'ncert-doc-economics', documentVersionId: 'ncert-doc-economics-v1', chapterId: 'ncert-chapter-eco-5', pageId: 'ncert-page-eco-5', excerpt: '[demonstration excerpt — see jess205.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-eco-5', unitId: 'ncert-unit-economics', title: 'Consumer Rights', order: 5, sourceDocumentId: 'ncert-doc-economics' })
ncertLessons.push({ id: 'ncert-lesson-eco-5', chapterId: 'ncert-chapter-eco-5', title: 'Consumer Rights', order: 1, conceptIds: ['ncert-concept-eco-5-1', 'ncert-concept-eco-5-2'] })
ncertConcepts.push({ id: 'ncert-concept-eco-5-1', title: 'Consumer rights framework', description: 'The specific enumerated rights (safety, information, choice, redressal, among others) the chapter identifies as protecting consumers.', domain: 'Economics' })
ncertConcepts.push({ id: 'ncert-concept-eco-5-2', title: 'Redressal mechanisms', description: 'The tiered consumer-court system (district, state, national) described in the chapter, and what determines which level a complaint goes to.', domain: 'Economics' })
ncertExplanations.push({ id: 'ncert-explanation-eco-5-1', conceptId: 'ncert-concept-eco-5-1', body: 'The rights a consumer holds against unfair or unsafe market practices, and the specific institutional mechanisms that exist to enforce them in practice.', sourceReferenceIds: ['ncert-ref-eco-5'] })
ncertExplanations.push({ id: 'ncert-explanation-eco-5-2', conceptId: 'ncert-concept-eco-5-2', body: 'The tiered consumer-court system (district, state, national) described in the chapter, and what determines which level a complaint goes to.', sourceReferenceIds: ['ncert-ref-eco-5'] })
ncertExamples.push({ id: 'ncert-example-eco-5', conceptId: 'ncert-concept-eco-5-1', prompt: 'Guided analysis: which right was violated, and where to file', steps: ['Identify a specific consumer-rights violation scenario from the chapter.', 'Identify which enumerated right it violates.', 'Identify which level of redressal mechanism would be appropriate for a complaint of that scale.'], sourceReferenceIds: ['ncert-ref-eco-5'] })
ncertActivities.push({ id: 'ncert-activity-eco-5', lessonId: 'ncert-lesson-eco-5', kind: 'discussion' as LearningActivityKind, title: 'Discuss a real or plausible situation where a consumer right described in the chapter was violated, and what recourse existed.', instructions: 'Using the chapter\'s framework, explain why consumer redressal is organised in tiers rather than a single national body.' })
ncertQuestions.push({ id: 'ncert-question-eco-5-transfer', conceptId: 'ncert-concept-eco-5-1', kind: 'transfer', prompt: 'Apply the consumer-rights framework to a purchase or transaction scenario not explicitly covered in the chapter.', answerKeyEntryId: 'ncert-answerkey-eco-5-transfer', sourceReferenceIds: ['ncert-ref-eco-5'] })
// eco-5: source jess2dd/jess205.pdf sha256=d1c546bbf35a4133...

// ---------------------------------------------------------------------------
// Political Science — Democratic Politics II
// ---------------------------------------------------------------------------

ncertCourses.push({ id: 'ncert-course-polisci', curriculumId: NCERT_CURRICULUM_ID, title: 'Political Science — Democratic Politics II', gradeLevel: 'Grade 10' })
ncertUnits.push({ id: 'ncert-unit-polisci', courseId: 'ncert-course-polisci', title: 'Political Science — Democratic Politics II', order: 1 })
ncertLearningSpaces.push({ id: 'ncert-space-polisci', title: 'Political Science — Democratic Politics II', curriculumId: NCERT_CURRICULUM_ID, ownerId: OWNER_ID, currentVersionId: 'ncert-space-polisci-v1', lifecycleState: 'published' })
ncertDocuments.push({ id: 'ncert-doc-polisci', title: 'Political Science — Democratic Politics II', sourceLabel: 'NCERT Class X — private development/demonstration corpus only', ownerId: OWNER_ID, currentVersionId: 'ncert-doc-polisci-v1', publicationStatus: 'published', contentHash: 'c4808f2cde54910812bc324560f62149654caa4bda282c64b3965451905ff22f', sourceType: 'textbook', accessClassification: 'institution_private', processingState: 'extracted', sourceRightsDeclaration: 'development_demonstration_only' })
ncertDocumentVersions.push({ id: 'ncert-doc-polisci-v1', documentId: 'ncert-doc-polisci', version: 1, createdAt: '2026-07-27T00:00:00.000Z', extractionMethod: 'native_pdf', extractionProvider: 'native_pdf_v1' })
ncertPages.push({ id: 'ncert-page-pol-1', documentVersionId: 'ncert-doc-polisci-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-pol-1', documentId: 'ncert-doc-polisci', documentVersionId: 'ncert-doc-polisci-v1', chapterId: 'ncert-chapter-pol-1', pageId: 'ncert-page-pol-1', excerpt: '[demonstration excerpt — see jess401.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-pol-1', unitId: 'ncert-unit-polisci', title: 'Power-sharing', order: 1, sourceDocumentId: 'ncert-doc-polisci' })
ncertLessons.push({ id: 'ncert-lesson-pol-1', chapterId: 'ncert-chapter-pol-1', title: 'Power-sharing', order: 1, conceptIds: ['ncert-concept-pol-1-1', 'ncert-concept-pol-1-2'] })
ncertConcepts.push({ id: 'ncert-concept-pol-1-1', title: 'Horizontal and vertical power-sharing', description: 'Power divided among organs of government at the same level (horizontal — legislature/executive/judiciary) versus across different levels of government (vertical — union/state/local).', domain: 'Political Science' })
ncertConcepts.push({ id: 'ncert-concept-pol-1-2', title: 'Majoritarianism vs. power-sharing', description: 'The chapter\'s contrast between rule by a single majority group (associated with instability in its Sri Lanka example) and negotiated power-sharing (associated with stability in its Belgium example).', domain: 'Political Science' })
ncertExplanations.push({ id: 'ncert-explanation-pol-1-1', conceptId: 'ncert-concept-pol-1-1', body: 'Why dividing power among different institutions and groups is treated as prudent for a stable democracy, not merely a compromise forced on it.', sourceReferenceIds: ['ncert-ref-pol-1'] })
ncertExplanations.push({ id: 'ncert-explanation-pol-1-2', conceptId: 'ncert-concept-pol-1-2', body: 'The chapter\'s contrast between rule by a single majority group (associated with instability in its Sri Lanka example) and negotiated power-sharing (associated with stability in its Belgium example).', sourceReferenceIds: ['ncert-ref-pol-1'] })
ncertExamples.push({ id: 'ncert-example-pol-1', conceptId: 'ncert-concept-pol-1-1', prompt: 'Guided analysis: comparing Belgium and Sri Lanka', steps: ['Identify the power-sharing arrangement described for Belgium.', 'Identify the majoritarian approach described for Sri Lanka.', 'Explain what specific outcome the chapter attributes to each choice.'], sourceReferenceIds: ['ncert-ref-pol-1'] })
ncertActivities.push({ id: 'ncert-activity-pol-1', lessonId: 'ncert-lesson-pol-1', kind: 'discussion' as LearningActivityKind, title: 'Discuss: what does the Belgium/Sri Lanka comparison suggest about why power-sharing is prudent, not just fair?', instructions: 'Using the chapter\'s own reasoning, explain the difference between the "moral" and the "prudential" case for power-sharing.' })
ncertQuestions.push({ id: 'ncert-question-pol-1-transfer', conceptId: 'ncert-concept-pol-1-1', kind: 'transfer', prompt: 'Apply the horizontal/vertical power-sharing distinction to a country or institution you are aware of outside these two examples.', answerKeyEntryId: 'ncert-answerkey-pol-1-transfer', sourceReferenceIds: ['ncert-ref-pol-1'] })
// pol-1: source jess4dd/jess401.pdf sha256=f196321f2b8b61df...
ncertPages.push({ id: 'ncert-page-pol-2', documentVersionId: 'ncert-doc-polisci-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-pol-2', documentId: 'ncert-doc-polisci', documentVersionId: 'ncert-doc-polisci-v1', chapterId: 'ncert-chapter-pol-2', pageId: 'ncert-page-pol-2', excerpt: '[demonstration excerpt — see jess402.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-pol-2', unitId: 'ncert-unit-polisci', title: 'Federalism', order: 2, sourceDocumentId: 'ncert-doc-polisci' })
ncertLessons.push({ id: 'ncert-lesson-pol-2', chapterId: 'ncert-chapter-pol-2', title: 'Federalism', order: 1, conceptIds: ['ncert-concept-pol-2-1', 'ncert-concept-pol-2-2'] })
ncertConcepts.push({ id: 'ncert-concept-pol-2-1', title: 'Federal vs. unitary systems', description: 'The structural difference between a federation (constitutionally guaranteed division of power between levels) and a unitary system (a single level holds ultimate authority) — with the chapter\'s own examples of each.', domain: 'Political Science' })
ncertConcepts.push({ id: 'ncert-concept-pol-2-2', title: 'Third-tier government', description: 'Why the chapter treats local government (panchayats/municipalities) as a distinct, constitutionally significant tier, not merely an administrative convenience of the states.', domain: 'Political Science' })
ncertExplanations.push({ id: 'ncert-explanation-pol-2-1', conceptId: 'ncert-concept-pol-2-1', body: 'How federal systems divide power between different levels of government by design, and what the chapter identifies as necessary for that division to actually hold in practice.', sourceReferenceIds: ['ncert-ref-pol-2'] })
ncertExplanations.push({ id: 'ncert-explanation-pol-2-2', conceptId: 'ncert-concept-pol-2-2', body: 'Why the chapter treats local government (panchayats/municipalities) as a distinct, constitutionally significant tier, not merely an administrative convenience of the states.', sourceReferenceIds: ['ncert-ref-pol-2'] })
ncertExamples.push({ id: 'ncert-example-pol-2', conceptId: 'ncert-concept-pol-2-1', prompt: 'Guided analysis: what makes a federation "federal" in practice', steps: ['Identify one constitutional feature the chapter says a genuine federation requires (e.g. an independent judiciary to arbitrate disputes).', 'Identify a case in the chapter where that feature mattered.', 'Explain what would happen to federalism without that feature.'], sourceReferenceIds: ['ncert-ref-pol-2'] })
ncertActivities.push({ id: 'ncert-activity-pol-2', lessonId: 'ncert-lesson-pol-2', kind: 'discussion' as LearningActivityKind, title: 'Discuss why the chapter considers the 1992 constitutional amendments establishing local government a significant expansion of Indian federalism.', instructions: 'Using the chapter\'s own criteria, explain what distinguishes a federation from a unitary system that has merely decentralised some administration.' })
ncertQuestions.push({ id: 'ncert-question-pol-2-transfer', conceptId: 'ncert-concept-pol-2-1', kind: 'transfer', prompt: 'Apply the federal/unitary distinction to a governmental structure you are aware of outside India.', answerKeyEntryId: 'ncert-answerkey-pol-2-transfer', sourceReferenceIds: ['ncert-ref-pol-2'] })
// pol-2: source jess4dd/jess402.pdf sha256=b8e30317fdd6085e...
ncertPages.push({ id: 'ncert-page-pol-3', documentVersionId: 'ncert-doc-polisci-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-pol-3', documentId: 'ncert-doc-polisci', documentVersionId: 'ncert-doc-polisci-v1', chapterId: 'ncert-chapter-pol-3', pageId: 'ncert-page-pol-3', excerpt: '[demonstration excerpt — see jess403.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-pol-3', unitId: 'ncert-unit-polisci', title: 'Gender, Religion and Caste', order: 3, sourceDocumentId: 'ncert-doc-polisci' })
ncertLessons.push({ id: 'ncert-lesson-pol-3', chapterId: 'ncert-chapter-pol-3', title: 'Gender, Religion and Caste', order: 1, conceptIds: ['ncert-concept-pol-3-1', 'ncert-concept-pol-3-2'] })
ncertConcepts.push({ id: 'ncert-concept-pol-3-1', title: 'Social divisions and democracy', description: 'The chapter\'s core claim that social divisions do not automatically threaten democracy — how they are politically expressed is what matters.', domain: 'Political Science' })
ncertConcepts.push({ id: 'ncert-concept-pol-3-2', title: 'Communalism vs. secularism', description: 'The distinction between communalism (one religious community organised against others) and the constitutional principle of secularism the chapter presents as the alternative.', domain: 'Political Science' })
ncertExplanations.push({ id: 'ncert-explanation-pol-3-1', conceptId: 'ncert-concept-pol-3-1', body: 'Why social divisions based on gender, religion, and caste show up in democratic politics, and the chapter\'s distinction between healthy political expression of a divide and its unhealthy, destabilising form.', sourceReferenceIds: ['ncert-ref-pol-3'] })
ncertExplanations.push({ id: 'ncert-explanation-pol-3-2', conceptId: 'ncert-concept-pol-3-2', body: 'The distinction between communalism (one religious community organised against others) and the constitutional principle of secularism the chapter presents as the alternative.', sourceReferenceIds: ['ncert-ref-pol-3'] })
ncertExamples.push({ id: 'ncert-example-pol-3', conceptId: 'ncert-concept-pol-3-1', prompt: 'Guided analysis: healthy vs. unhealthy political expression of a divide', steps: ['Identify one example in the chapter of a social division expressed through legitimate political demand.', 'Identify one example of the same kind of division expressed destructively (e.g. communal violence).', 'Explain what specifically distinguishes the two, per the chapter.'], sourceReferenceIds: ['ncert-ref-pol-3'] })
ncertActivities.push({ id: 'ncert-activity-pol-3', lessonId: 'ncert-lesson-pol-3', kind: 'discussion' as LearningActivityKind, title: 'Discuss why the chapter argues that gender, caste, and religion-based divisions are not inherently a problem for democracy.', instructions: 'Using the chapter\'s distinction, explain the difference between a legitimate political mobilisation around identity and communalism.' })
ncertQuestions.push({ id: 'ncert-question-pol-3-transfer', conceptId: 'ncert-concept-pol-3-1', kind: 'transfer', prompt: 'Apply the "expression matters more than the division itself" idea to a social division you are aware of, in India or elsewhere.', answerKeyEntryId: 'ncert-answerkey-pol-3-transfer', sourceReferenceIds: ['ncert-ref-pol-3'] })
// pol-3: source jess4dd/jess403.pdf sha256=29742b10357d4a07...
ncertPages.push({ id: 'ncert-page-pol-4', documentVersionId: 'ncert-doc-polisci-v1', pageNumber: 2, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-pol-4', documentId: 'ncert-doc-polisci', documentVersionId: 'ncert-doc-polisci-v1', chapterId: 'ncert-chapter-pol-4', pageId: 'ncert-page-pol-4', excerpt: '[demonstration excerpt — see jess404.pdf p.2]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-pol-4', unitId: 'ncert-unit-polisci', title: 'Political Parties', order: 4, sourceDocumentId: 'ncert-doc-polisci' })
ncertLessons.push({ id: 'ncert-lesson-pol-4', chapterId: 'ncert-chapter-pol-4', title: 'Political Parties', order: 1, conceptIds: ['ncert-concept-pol-4-1', 'ncert-concept-pol-4-2'] })
ncertConcepts.push({ id: 'ncert-concept-pol-4-1', title: 'Functions of political parties', description: 'The specific functions the chapter attributes to parties — contesting elections, forming and running government, shaping policy, providing opposition and accountability — beyond simply "winning elections."', domain: 'Political Science' })
ncertConcepts.push({ id: 'ncert-concept-pol-4-2', title: 'Evolution of India\'s party system', description: 'The chapter\'s account of the shift from one-party dominance to a genuinely multi-party, often coalition-based system.', domain: 'Political Science' })
ncertExplanations.push({ id: 'ncert-explanation-pol-4-1', conceptId: 'ncert-concept-pol-4-1', body: 'Why democracies need political parties specifically (not just elections), and the chapter\'s account of how India\'s party system evolved from single-party dominance toward today\'s multi-party competition.', sourceReferenceIds: ['ncert-ref-pol-4'] })
ncertExplanations.push({ id: 'ncert-explanation-pol-4-2', conceptId: 'ncert-concept-pol-4-2', body: 'The chapter\'s account of the shift from one-party dominance to a genuinely multi-party, often coalition-based system.', sourceReferenceIds: ['ncert-ref-pol-4'] })
ncertExamples.push({ id: 'ncert-example-pol-4', conceptId: 'ncert-concept-pol-4-1', prompt: 'Guided analysis: why elections alone are not enough', steps: ['Identify one function of political parties the chapter names beyond contesting elections.', 'Explain why that function could not be performed by voters or candidates acting individually, without parties.', 'Identify what the chapter says changed as India moved away from one-party dominance.'], sourceReferenceIds: ['ncert-ref-pol-4'] })
ncertActivities.push({ id: 'ncert-activity-pol-4', lessonId: 'ncert-lesson-pol-4', kind: 'discussion' as LearningActivityKind, title: 'Discuss which function of political parties you think matters most for democratic accountability, and why.', instructions: 'Using the chapter\'s own functions list, explain why a democracy with elections but no organised parties would struggle to form a stable government.' })
ncertQuestions.push({ id: 'ncert-question-pol-4-transfer', conceptId: 'ncert-concept-pol-4-1', kind: 'transfer', prompt: 'Apply the "functions of a political party" framework to a specific party or party system you are aware of, in India or elsewhere.', answerKeyEntryId: 'ncert-answerkey-pol-4-transfer', sourceReferenceIds: ['ncert-ref-pol-4'] })
// pol-4: source jess4dd/jess404.pdf sha256=848863f8ebe983fe...
ncertPages.push({ id: 'ncert-page-pol-5', documentVersionId: 'ncert-doc-polisci-v1', pageNumber: 1, extractedText: '[private demonstration excerpt — not reproduced publicly]', extractionConfidence: 0.95, pageExtractionMethod: 'native_pdf', qualityState: 'reliable' })
ncertSourceReferences.push({ id: 'ncert-ref-pol-5', documentId: 'ncert-doc-polisci', documentVersionId: 'ncert-doc-polisci-v1', chapterId: 'ncert-chapter-pol-5', pageId: 'ncert-page-pol-5', excerpt: '[demonstration excerpt — see jess405.pdf p.1]', extractionConfidence: 0.95 })
ncertChapters.push({ id: 'ncert-chapter-pol-5', unitId: 'ncert-unit-polisci', title: 'Outcomes of Democracy', order: 5, sourceDocumentId: 'ncert-doc-polisci' })
ncertLessons.push({ id: 'ncert-lesson-pol-5', chapterId: 'ncert-chapter-pol-5', title: 'Outcomes of Democracy', order: 1, conceptIds: ['ncert-concept-pol-5-1', 'ncert-concept-pol-5-2'] })
ncertConcepts.push({ id: 'ncert-concept-pol-5-1', title: 'Criteria for evaluating democracy', description: 'The chapter\'s specific criteria — government accountability, quality of decision-making, respect for citizen dignity, and reduction of economic/social inequality — used to judge outcomes rather than the mere existence of elections.', domain: 'Political Science' })
ncertConcepts.push({ id: 'ncert-concept-pol-5-2', title: 'Accountability and legitimacy', description: 'Why the chapter treats democracy\'s legitimacy (people preferring it even when frustrated with a specific government) as distinct from its actual policy performance.', domain: 'Political Science' })
ncertExplanations.push({ id: 'ncert-explanation-pol-5-1', conceptId: 'ncert-concept-pol-5-1', body: 'How to judge whether a democracy is actually working, using specific criteria (accountability, legitimacy, reduction of inequality) rather than treating "is it a democracy" as a yes/no question.', sourceReferenceIds: ['ncert-ref-pol-5'] })
ncertExplanations.push({ id: 'ncert-explanation-pol-5-2', conceptId: 'ncert-concept-pol-5-2', body: 'Why the chapter treats democracy\'s legitimacy (people preferring it even when frustrated with a specific government) as distinct from its actual policy performance.', sourceReferenceIds: ['ncert-ref-pol-5'] })
ncertExamples.push({ id: 'ncert-example-pol-5', conceptId: 'ncert-concept-pol-5-1', prompt: 'Guided analysis: distinguishing "the government failed" from "democracy failed"', steps: ['Identify an example in the chapter of citizens frustrated with a specific government\'s performance.', 'Identify what the chapter says about whether that frustration extends to rejecting democracy itself.', 'Explain why the chapter treats these as two separate judgments.'], sourceReferenceIds: ['ncert-ref-pol-5'] })
ncertActivities.push({ id: 'ncert-activity-pol-5', lessonId: 'ncert-lesson-pol-5', kind: 'discussion' as LearningActivityKind, title: 'Discuss why the chapter argues that legitimacy and day-to-day performance are two separate measures of a democracy\'s success.', instructions: 'Using the chapter\'s criteria, evaluate a democratic outcome (real or hypothetical) against at least two of the named criteria.' })
ncertQuestions.push({ id: 'ncert-question-pol-5-transfer', conceptId: 'ncert-concept-pol-5-1', kind: 'transfer', prompt: 'Apply the "separate legitimacy from performance" distinction to a political situation you are aware of, in India or elsewhere.', answerKeyEntryId: 'ncert-answerkey-pol-5-transfer', sourceReferenceIds: ['ncert-ref-pol-5'] })
// pol-5: source jess4dd/jess405.pdf sha256=f9049b6789da5964...
